#!/usr/bin/python3

# Create a default options.ini for Kolibri

import configparser
import functools
import os
import shutil
from pathlib import Path

EIB_KOLIBRI_REGULAR_USERS_CAN_MANAGE_CONTENT = os.environ.get(
    "EIB_KOLIBRI_REGULAR_USERS_CAN_MANAGE_CONTENT"
)

config = configparser.ConfigParser()

# By default, ConfigParser converts option names to a lowercase "canonical"
# form. Instead, we want it to leave them alone.
config.optionxform = lambda name: name

if EIB_KOLIBRI_REGULAR_USERS_CAN_MANAGE_CONTENT == "true":
    try:
        config.add_section("DesktopAuth")
    except configparser.DuplicateSectionError:
        pass
    config.set("DesktopAuth", "REGULAR_USERS_CAN_MANAGE_CONTENT", "True")

config_count = functools.reduce(
    lambda total, section: total + len(section), config.values(), 0
)

EIB_TMPDIR = Path(os.environ.get("EIB_TMPDIR"))
TMP_OPTIONS_FILE_PATH = Path(EIB_TMPDIR, "options.ini")
if config_count > 0:
    with open(TMP_OPTIONS_FILE_PATH, "w") as options_file:
        config.write(options_file)

    if "EIB_KOLIBRI_INSTALL_CHANNELS" in os.environ:
        OSTREE_VAR = Path(os.environ.get("OSTREE_VAR"))
        KOLIBRI_HOME = Path(OSTREE_VAR, "lib/kolibri/data")
        shutil.copy(TMP_OPTIONS_FILE_PATH, KOLIBRI_HOME)

    if "EIB_ENDLESSKEY_INSTALL_CHANNELS" in os.environ:
        OSTREE_VAR = Path(os.environ.get("OSTREE_VAR"))
        KOLIBRI_HOME = Path(OSTREE_VAR, "lib/endless-key/data")
        shutil.copy(TMP_OPTIONS_FILE_PATH, KOLIBRI_HOME)
