#!/usr/bin/python3

# Kill all the processes running in the specified chroot directory

import eib
import os
import sys

if len(sys.argv) < 2:
    print("No root path supplied", file=sys.stderr)

# Make sure we don't bring down the whole system
root = os.path.realpath(sys.argv[1])
if root == '/':
    print('Root cannot be /', file=sys.stderr)
    exit(1)

eib.setup_logging()
eib.kill_root_processes(root)
