#!/bin/bash -ex
# -*- mode: Shell-script; sh-basic-offset: 2; indent-tabs-mode: nil -*-
. "${EIB_BASELIB}"

# Split the existing full image into two files. One image file is for
# the main disk, and one is for a supplemental disk to be filled with
# apps.

kill_procs() {
  if [ -n "${OSTREE_DEPLOYMENT}" ]; then
    "${EIB_HELPERSDIR}"/kill-chroot-procs "${OSTREE_DEPLOYMENT}"
  fi
}

cleanup_loop() {
  partx -v -d "$1"
  eib_delete_loop "$1"
}

cleanup_devices() {
  [ -n "${DISK1_LOOP}" ] && cleanup_loop "${DISK1_LOOP}"
  [ -n "${DISK2_LOOP}" ] && cleanup_loop "${DISK2_LOOP}"
  unset DISK1_LOOP DISK2_LOOP
}

cleanup() {
  kill_procs || :
  eib_umount_all || :
  cleanup_devices || :
}
trap cleanup EXIT

# Shrink the disk1 image after migration to extra storage.
shrink_disk1_image() {
  local disk1_img=$1

  # Calculate the shrunken root fs size from the esimated minimum. The
  # minimum size is in blocks, which are assumed to be 4kB.
  e2fsck -f -p "${ROOT_LOOP}"
  local root_part_min_blocks
  root_part_min_blocks=$(resize2fs -P $ROOT_LOOP | \
    awk '/^Estimated minimum size/{print $NF}')

  local root_part_size
  root_part_size=$((root_part_min_blocks * 4096))

  # Calculate the new total disk1 size
  local new_disk1_img_size=$root_part_size
  local old_disk1_img_size old_disk1_root_size
  old_disk1_img_size=$(blockdev --getsize64 $DISK1_LOOP)
  old_disk1_root_size=$(blockdev --getsize64 $ROOT_LOOP)

  # Add the same number of sectors before and after the root partition
  (( new_disk1_img_size += old_disk1_img_size - old_disk1_root_size))

  # After booting, the root fs will be expanded to fill any available
  # space, and we want to provide 1 GiB of free space on the device. The
  # actual "16 GB" eMMC device on Intel Sqwerty was 15758000128 bytes,
  # but we'll assume 98% available space, which is 15680000000 bytes.
  # Fail if the image won't fit in this space.
  disk1_size=${EIB_IMAGE_DISK1_SIZE}
  local disk1_max_img_size
  disk1_max_img_size=$(python -c "print int(${disk1_size} * 0.98)")
  ((disk1_max_img_size -= 1 * 2**30))
  if ((new_disk1_img_size > disk1_max_img_size)); then
    echo "ERROR: ${EIB_PERSONALITY} disk1 image exceeds" \
         "${disk1_max_img_size}" >&2
    return 1
  fi

  # So we don't perform the initial boot with a totally full root, add
  # 100MB of initial free space.
  ((root_part_size += 100 * 2**20))
  ((new_disk1_img_size += 100 * 2**20))

  if ((new_disk1_img_size >= old_disk1_img_size)); then
    echo "Avoid growing ${EIB_PERSONALITY} disk1 image to ${new_disk1_img_size}"
    return 0
  fi

  echo "Creating ${EIB_PERSONALITY} disk1 image with size ${new_disk1_img_size}"

  # Resize the root fs, specifying sectors from bytes.
  local root_part_len=$((root_part_size / 512))
  e2fsck -f -p "${ROOT_LOOP}"
  resize2fs "${ROOT_LOOP}" "${root_part_len}s"

  # Read the current partition table. Must be done before truncating the
  # image; sfdisk doesn't manage to read the GPT from the truncated image
  # because it has lost the GPT backup.
  local orig_partitions
  orig_partitions=$(sfdisk -d "${disk1_img}")

  # We need to avoid presenting the 0B marker partition to the next 'sfdisk'
  # call since the latest version doesn't recognize this as a valid partition.
  # We will recreate it again after the resize.
  if [ "${EIB_IMAGE_PARTITION_TABLE}" == "dos" ]  && [ "${EIB_IMAGE_ROOTFS_RESIZE}" == "true" ]; then
	  orig_partitions=$(echo "$orig_partitions" | sed -e '$d')
  fi

  # Resize the image file first, to try to later catch errors in the partition
  # setup.
  truncate -s ${new_disk1_img_size} "${disk1_img}"

  # Adjust and restore the partition table
  # last-lba is removed for sfdisk to recompute
  # The final partition is sized according to our calculations
  echo "${orig_partitions}" | sed \
	-e '/^last-lba:/d' \
	-e "$ s/size=[0-9\t ]*,/size=${root_part_len},/" |
	sfdisk --force "${disk1_img}"

  if [ "${EIB_IMAGE_PARTITION_TABLE}" == "dos" ]  && [ "${EIB_IMAGE_ROOTFS_RESIZE}" == "true" ]; then
      # Add magic marker on 4th partition to signal resizing is wanted
      printf "\xdd" | dd of=${disk1_img} bs=1 count=1 seek=498 conv=notrunc
  fi
}

# Shrink the disk2 image after migration to extra storage.
shrink_disk2_image() {
  local disk2_img=$1

  # Calculate the shrunken extra fs size from the esimated minimum. The
  # minimum size is in blocks, which are assumed to be 4kB.
  e2fsck -f -p "${EXTRA_LOOP}"
  local extra_part_min_blocks
  extra_part_min_blocks=$(resize2fs -P $EXTRA_LOOP | \
    awk '/^Estimated minimum size/{print $NF}')
  local extra_part_size=$((extra_part_min_blocks * 4096))

  # Calculate the new total disk1 size
  local new_disk2_img_size=$extra_part_size
  local old_disk2_img_size old_disk2_extra_size
  old_disk2_img_size=$(blockdev --getsize64 $DISK2_LOOP)
  old_disk2_extra_size=$(blockdev --getsize64 $EXTRA_LOOP)

  # Add the same number of sectors before and after the partition
  (( new_disk2_img_size += old_disk2_img_size - old_disk2_extra_size))

  echo "Creating ${EIB_PERSONALITY} disk2 image with size ${new_disk2_img_size}"

  # Resize the extra fs, specifying sectors from bytes.
  local extra_part_len=$((extra_part_size / 512))
  e2fsck -f -p "${EXTRA_LOOP}"
  resize2fs "${EXTRA_LOOP}" "${extra_part_len}s"

  # Read the current partition table. Must be done before truncating the
  # image; sfdisk doesn't manage to read the GPT from the truncated image
  # because it has lost the GPT backup.
  local orig_partitions
  orig_partitions=$(sfdisk -d "${disk2_img}")

  # Resize the image file first to try to catch errors in the partition
  # setup.
  truncate -s ${new_disk2_img_size} "${disk2_img}"

  # Adjust and restore the partition table
  # last-lba is removed for sfdisk to recompute
  # The final partition is sized according to our calculations
  echo "${orig_partitions}" | sed \
	-e '/^last-lba:/d' \
	-e "$ s/size=[0-9\t ]*,/size=${extra_part_len},/" |
	sfdisk --force "${disk2_img}"

  if [ "${EIB_IMAGE_PARTITION_TABLE}" == "dos" ] && [ "${EIB_IMAGE_ROOTFS_RESIZE}" == "true" ]; then
      # Add magic marker on 4th partition to signal resizing is wanted
      printf "\xdd" | dd of=${disk2_img} bs=1 count=1 seek=498 conv=notrunc
  fi

}

split_image() {
  local disk1_img=$1
  local disk2_img=${EIB_TMPDIR}/disk2

  local disk1_zimg disk2_zimg
  disk1_zimg=$(eib_outfile disk1.img.${EIB_IMAGE_COMPRESSION})
  disk2_zimg=$(eib_outfile disk2.img.${EIB_IMAGE_COMPRESSION})

  local disk1_img_asc disk2_img_asc
  disk1_img_asc=$(eib_outfile disk1.img.asc)
  disk2_img_asc=$(eib_outfile disk2.img.asc)

  # Mount root filesystem from the last partition of the image file.
  DISK1_LOOP=$(losetup --show -f "${disk1_img}")
  eib_partx_scan "${DISK1_LOOP}"
  local disk1_parts=( "${DISK1_LOOP}"p* )
  ROOT_LOOP="${disk1_parts[-1]}"
  ROOT=${EIB_TMPDIR}/mnt
  recreate_dir "${ROOT}"
  eib_mount -t ext4 "${ROOT_LOOP}" "${ROOT}"

  # Redefine ostree variables based on ROOT mount point so they appear
  # the same to split hooks
  export OSTREE_DEPLOYMENT="${ROOT}"/ostree/deploy/${EIB_OSTREE_OS}/deploy/${OSTREE_CURRENT_DEPLOYMENT}
  export OSTREE_VAR="${ROOT}"/ostree/deploy/${EIB_OSTREE_OS}/var

  # Mount the deployment directory over itself so / is a real mount in
  # the chroot. This is needed for bubblewrap, which wants to mark the /
  # mount as a slave.
  eib_mount --bind "${OSTREE_DEPLOYMENT}" "${OSTREE_DEPLOYMENT}"

  # Mark the hook root mount private. This has 2 benefits:
  #
  # 1. Any mounts placed under it will not leak out to the parent mount.
  #    That keeps aliased mounts from showing up elsewhere in the
  #    system.
  #
  # 2. Bubblewrap uses pivot_root, which requires that the old root is
  #    not a shared mount.
  mount --make-private "${OSTREE_DEPLOYMENT}"

  # Finally, pivot_root also requires that the parent of the old root is
  # not a shared mount. Bind mount the hook root over itself again so
  # the parent is the above private mount.
  #
  # See https://github.com/projectatomic/bubblewrap/issues/135.
  eib_mount --bind "${OSTREE_DEPLOYMENT}" "${OSTREE_DEPLOYMENT}"

  # Bind mount the ostree /var into the current deployment so it
  # resembles the booted system.
  eib_mount --bind "${OSTREE_VAR}" "${OSTREE_DEPLOYMENT}"/var

  # Create disk2 image file with 1 partition for our "16 GB" SD card.
  # The actual size might vary and we want to be a little connservative,
  # so use 98% of 16 GB, which is 15680000000 bytes.
  rm -f "${disk2_img}"
  disk2_size=${EIB_IMAGE_DISK2_SIZE}
  local disk2_img_size
  disk2_img_size=$(python -c "print int(${disk2_size} * 0.98)")
  truncate -s ${disk2_img_size} "${disk2_img}"

  pt_label=${EIB_IMAGE_PARTITION_TABLE}
  if [ "${EIB_IMAGE_PARTITION_TABLE}" == "dos" ]; then
    part_type="83"
  else
    part_type="0FC63DAF-8483-4772-8E79-3D69D8477DE4"
    case "${EIB_ARCH}" in
      i386|amd64)
        ext4_opts="dir_index,^huge_file"
        ;;
      *)
        ext4_opts="dir_index,^huge_file,^64bit"
        ;;
    esac
  fi

  # Attr 55 indicates that the partition should be resized later.
  echo "start=2048, type=${part_type}, attrs=GUID:55" | sfdisk --force --label "${pt_label}" "${disk2_img}"

  # Split files from the root filesystem into extra. Let the hooks know
  # where the extra filesystem is mounted.
  export EIB_EXTRA_MOUNT=/var/endless-extra

  # Create disk2 filesystem and mount it on top of the above bind mount.
  DISK2_LOOP=$(losetup --show -f "${disk2_img}")
  eib_partx_scan "${DISK2_LOOP}"
  EXTRA_LOOP="${DISK2_LOOP}p1"
  mke2fs -t ext4 -O ${ext4_opts} -m1 -L extra "${EXTRA_LOOP}"
  export OSTREE_EXTRA="${OSTREE_DEPLOYMENT}${EIB_EXTRA_MOUNT}"
  recreate_dir "${OSTREE_EXTRA}"
  eib_mount -t ext4 "${EXTRA_LOOP}" "${OSTREE_EXTRA}"
  eib_write_version_xattr "${OSTREE_EXTRA}"

  # Mount kernel filesystems into deployment for split hooks
  eib_mount -t sysfs sysfs "${OSTREE_DEPLOYMENT}"/sys
  eib_mount -t proc proc "${OSTREE_DEPLOYMENT}"/proc
  eib_mount --bind /dev "${OSTREE_DEPLOYMENT}"/dev
  eib_mount --bind /dev/pts "${OSTREE_DEPLOYMENT}"/dev/pts

  # Mount a tmpfs at /tmp so that hooks can use it without persisting to
  # the image
  eib_mount -t tmpfs tmpfs "${OSTREE_DEPLOYMENT}"/tmp

  # Bind mount the root over deployment's /sysroot, so the ostree repo
  # is available for split hooks
  eib_mount --bind "${ROOT}" "${OSTREE_DEPLOYMENT}"/sysroot

  # Bind mount the cache and source directories into the deployment so
  # chroot hooks can access them
  export EIB_CACHEDIR_CHROOT=/tmp/eos-image-builder
  export EIB_SRCDIR_CHROOT=${EIB_CACHEDIR_CHROOT}/src
  mkdir -p "${OSTREE_DEPLOYMENT}${EIB_CACHEDIR_CHROOT}" \
        "${OSTREE_DEPLOYMENT}${EIB_SRCDIR_CHROOT}"
  eib_mount --bind "${EIB_CACHEDIR}" \
            "${OSTREE_DEPLOYMENT}${EIB_CACHEDIR_CHROOT}"
  eib_mount --bind "${EIB_SRCDIR}" \
            "${OSTREE_DEPLOYMENT}${EIB_SRCDIR_CHROOT}"

  # Copy in the host's /etc/resolv.conf so the one from the ostree (if
  # it exists) is not used and DNS can be resolved.
  cp -f /etc/resolv.conf "${OSTREE_DEPLOYMENT}"/etc/resolv.conf

  run_hooks split "${OSTREE_DEPLOYMENT}"
  "${EIB_HELPERSDIR}"/kill-chroot-procs "${OSTREE_DEPLOYMENT}"

  # Enable /var/endless-extra mount unit for the split image.
  mkdir -p "${OSTREE_DEPLOYMENT}"/etc/systemd/system/local-fs.target.wants
  ln -sf "/lib/systemd/system/var-endless\x2dextra.mount" \
    "${OSTREE_DEPLOYMENT}"/etc/systemd/system/local-fs.target.wants/

  # Clear the cache and source mount variables in case they're used
  # somewhere else
  unset EIB_CACHEDIR_CHROOT EIB_SRCDIR_CHROOT

  # Delete the resolv.conf copy so it's not shipped
  rm -f "${OSTREE_DEPLOYMENT}"/etc/resolv.conf

  # Unmount the filesystems and shrink the image files.
  eib_umount_all
  shrink_disk1_image "${disk1_img}"
  shrink_disk2_image "${disk2_img}"

  # Temporarily remount the filesystem to fix the disk1 checksum using
  # the installed tool.
  eib_mount -t ext4 "${ROOT_LOOP}" "${ROOT}"
  eib_fix_boot_checksum "${DISK1_LOOP}" "${OSTREE_DEPLOYMENT}"
  eib_umount_all

  # Check the image for errors
  e2fsck -f -p "${ROOT_LOOP}"
  e2fsck -f -p "${EXTRA_LOOP}"
  udevadm settle

  # Delete loop devices and cleanup variables for the next iteration.
  cleanup_devices

  # Publish uncompressed file sizes.
  local disk1_extracted_size disk2_extracted_size
  disk1_extracted_size=$(stat -c "%s" "${disk1_img}")
  disk2_extracted_size=$(stat -c "%s" "${disk2_img}")
  echo "${disk1_extracted_size}" > "${disk1_zimg}.size"
  echo "${disk2_extracted_size}" > "${disk2_zimg}.size"

  # Create signatures for uncompressed images.
  sign_file "${disk1_img}" "${disk1_img_asc}" &
  sign_file "${disk2_img}" "${disk2_img_asc}" &

  # Compress image files.
  eib_compress_image "${disk1_img}" "${disk1_zimg}"
  eib_compress_image "${disk2_img}" "${disk2_zimg}"

  # Create signatures for compressed images.
  sign_file "${disk1_zimg}" &
  sign_file "${disk2_zimg}" &

  # Remove uncompressed images once signatures have been created.
  wait
  rm -f "${disk1_img}"
  rm -f "${disk2_img}"

  # Generate split disk manifest information
  local disk1_name disk1_compressed_size disk1_signature
  disk1_name=$(basename "${disk1_zimg}")
  disk1_compressed_size=$(stat -c "%s" "${disk1_zimg}")
  disk1_signature="${disk1_name}.asc"

  local disk2_name disk2_compressed_size disk2_signature
  disk2_name=$(basename "${disk2_zimg}")
  disk2_compressed_size=$(stat -c "%s" "${disk2_zimg}")
  disk2_signature="${disk2_name}.asc"
  cat > "${EIB_MANIFESTDIR}"/split-images.json <<EOF
{
  "images": {
    "disk1": {
      "file": "${disk1_name}",
      "extracted_size": ${disk1_extracted_size},
      "compressed_size": ${disk1_compressed_size},
      "compression_type": "${EIB_IMAGE_COMPRESSION}",
      "signature": "${disk1_signature}"
    },
    "disk2": {
      "file": "${disk2_name}",
      "extracted_size": ${disk2_extracted_size},
      "compressed_size": ${disk2_compressed_size},
      "compression_type": "${EIB_IMAGE_COMPRESSION}",
      "signature": "${disk2_signature}"
    }
  }
}
EOF
}

# Run main function for this image.
split_image "$@"
