#!/bin/bash -ex
# -*- mode: Shell-script; sh-basic-offset: 2; indent-tabs-mode: nil -*-
# Run the eib_error stage on errors. Return code 2 is used for image
# build failures to differentiate from locking failures.
stage_error() {
  eib_error
  exit 2
}
trap stage_error ERR

# Ensure basic settings are available from the environment.
for var in EIB_BASELIB EIB_SRCDIR EIB_CACHEDIR EIB_DATADIR \
  EIB_HELPERSDIR EIB_OUTDIR EIB_CHECKDIR EIB_TMPDIR EIB_CONTENTDIR
do
  if [ ! -v $var ]; then
    echo "error: required variable $var not set" >&2
    exit 1
  fi
done

. "${EIB_BASELIB}"

exec > >(tee "${EIB_TMPDIR}"/build.txt)
exec 2>&1

# Check if build needed and exit early if not
if eib_check_update && [ "${EIB_FORCE}" != true ]; then
  exit 0
fi

# Real build stages
eib_ostree
eib_image
eib_publish
