#!/bin/bash
MYDIR=$(dirname $(readlink -f $0))

(
	if ! flock -n 9; then
		echo "ERROR: instance already running" >&2
		exit 1
	fi

	cd $MYDIR
	git pull
	./build.sh $@
) 9>/var/tmp/eos-image-builder.lock
