#!/bin/bash -ex
export EOB_SRC=$(dirname $(readlink -f $0))
export EOB_BASELIB="${EOB_SRC}"/lib/eob.sh
export PATH=$EOB_SRC/stages:$PATH

export LANG=C
unset LANGUAGE LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
unset LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT LC_IDENTIFICATION
unset LC_ALL
export DEBIAN_FRONTEND=noninteractive
export DEBCONF_NONINTERACTIVE_SEEN=true
export DEBIAN_PRIORITY=critical

args=$(getopt -o "p:" -l "product:" -n "endless-os-builder" -- "$@")
eval set -- "${args}"

while true; do
  case "$1" in
    -p|--product)
      EOB_PRODUCT=$2
      shift 2
      ;;
    --)
      shift
      break
      ;;
  esac
done

# Some configuration defaults
# Debian package repository from where OS packages will be obtained
export EOB_OBS_REPO=http://obs-master.endlessm-sf.com:82/shared/eos

# GPG private key ID to sign ostree commit. The key with this ID must be
# available in /etc/image-utils/gnupg
export EOB_OSTREE_KEYID=4827DDED

# The ostree base URL that the final system will query for updates. Not used
# during build time. The product (e.g. eos) is taken as a subdirectory of
# this address.
export EOB_OSTREE_URL_BASE="http://endless:***REMOVED***@ostree.endlessm.com/staging/dev/"

# Size of built images
export EOB_IMAGE_SIZE=20GB

export EOB_BRANCH=${1:-dev}
export EOB_PRODUCT=${EOB_PRODUCT:-eos}

case "$(uname -m)" in
  x86_64|i?86)
    export EOB_ARCH=i386
    export EOB_PLATFORM=i386
    ;;

  arm*)
    export EOB_ARCH=armhf
    export EOB_PLATFORM=odroidu2
    ;;
esac

case "${EOB_PRODUCT}" in
  eos)
    export EOB_PERSONALITIES="Brazil Guatemala Global Positivo"
    ;;
  eosdev)
    export EOB_PERSONALITIES="Global"
    ;;
esac

export EOB_BUILD_VERSION=$(date +%y%m%d-%H%M%S)
export EOB_OSTREE_BRANCH=${EOB_BRANCH}/${EOB_PLATFORM}
export EOB_OSTREE_URL=${EOB_OSTREE_URL_BASE}/${EOB_PRODUCT}-${EOB_ARCH}

# Read user config overrides
[[ -e "${EOB_SRC}"/config ]] && . "${EOB_SRC}"/config

. "${EOB_BASELIB}"

recreate_dir "${EOB_OUTDIR}"
exec > >(tee $(eob_outfile build.txt))
exec 2>&1

mkdir -p "${EOB_CONTENT}"
. "${EOB_SRC}"/buildscript
