#!/bin/bash -ex
# -*- mode: Shell-script; sh-basic-offset: 2; indent-tabs-mode: nil -*-
. "${EIB_BASELIB}"

# Don't publish for a dry run.
[ "${EIB_DRY_RUN}" = true ] && exit 0

run_hooks publish

# Cleanup local output no longer needed to save space.
rm -rf "${EIB_OUTDIR}"
