#!/bin/bash -ex
# -*- mode: Shell-script; sh-basic-offset: 2; indent-tabs-mode: nil -*-
. "${EIB_BASELIB}"

# Pull in the latest commit.
eib_retry ostree --repo="${EIB_OSTREE_REPODIR}" pull \
  ${EIB_OSTREE_REMOTE} ${EIB_OSTREE_REF}

# Recreate the ref locally so that the deploy can pull from it
ostree --repo="${EIB_OSTREE_REPODIR}" refs --delete ${EIB_OSTREE_REF}
ostree --repo="${EIB_OSTREE_REPODIR}" refs --create=${EIB_OSTREE_REF} \
  ${EIB_OSTREE_REMOTE}:${EIB_OSTREE_REF}

# Update the major version ref if necessary. This will be used in the
# deployment instead of the minor version ref.
if [ "${EIB_OSTREE_REF_DEPLOY}" != "${EIB_OSTREE_REF}" ]; then
  ostree_write_refs "${EIB_OSTREE_REPODIR}" ${EIB_OSTREE_REF} \
    ${EIB_OSTREE_REF_DEPLOY}
fi

# Regenerate the summary file locally since pull --mirror will copy in
# the upstream summary file, which is inaccurate since only one ref was
# pulled and another ref was created locally.
ostree --repo="${EIB_OSTREE_REPODIR}" summary -u
