on:
  # The tests are currently only available on master, so only run when
  # pushing to master or pull requests targeting master.
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
    runs-on: ${{ matrix.os }}
    name: Run tests
    steps:
      - name: System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gpg \
            gpgv \
            python3-pip
      - name: Python dependencies
        run: |
          python3 -m pip install flake8 pytest
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: |
          python3 -m flake8
      - name: Tests
        run: |
          python3 -m pytest
