on:
  # The tests are currently only available on master, so only run when
  # pushing to master or pull requests targeting master.
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        flatpak-deps:
          - true
        include:
          - os: ubuntu-18.04
            # Flatpak on 18.04 is too old.
            flatpak-deps: false
    runs-on: ${{ matrix.os }}
    name: Run tests
    steps:
      - name: System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gir1.2-glib-2.0 \
            gir1.2-ostree-1.0 \
            gpg \
            gpgv \
            ostree \
            python3-gi \
            python3-pip
      - if: ${{ matrix.flatpak-deps }}
        name: System flatpak dependencies
        run: |
          sudo apt-get install -y \
            flatpak \
            gir1.2-flatpak-1.0
      - name: Python dependencies
        run: |
          python3 -m pip install pytest
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tests
        run: |
          python3 -m pytest
