on:
  # The tests are currently only available on master, so only run when
  # pushing to master or pull requests targeting master.
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    strategy:
      # Let other configurations continue if one fails.
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
    runs-on: ${{ matrix.os }}
    name: Run tests
    steps:
      - name: System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            flatpak \
            gir1.2-glib-2.0 \
            gir1.2-flatpak-1.0 \
            gir1.2-ostree-1.0 \
            gpg \
            gpgv \
            ostree \
            python3-gi \
            python3-pip
      - name: Checkout
        uses: actions/checkout@v2
      - name: Python dependencies
        run: |
          python3 -m pip install -r requirements-test.txt
      - name: Lint
        run: |
          python3 -m flake8
      - name: Tests
        run: |
          python3 -m pytest
